name: Deploy to ECS
on:
  push:
    branches:
      - main

env:
  AWS_ECR: public.ecr.aws/d9n7u6z3
  AWS_REPOSITORY_NAME: hello-world
  AWS_ECS_CLUSTER: hello-world-cluster
  AWS_ECS_TASK: hello-world-task
  AWS_ECS_SERVICE: hello-world-service


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR 
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR }}
          docker build -t $AWS_ECR/$AWS_REPOSITORY_NAME:$IMAGE_TAG .
          docker push $AWS_ECR/$AWS_REPOSITORY_NAME:$IMAGE_TAG
          echo "::set-output name=image::${{ secrets.AWS_ECR }}/$AWS_REPOSITORY:$IMAGE_TAG"
      
      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition --task-definition  ${{ env.AWS_ECS_TASK }} \
          --query taskDefinition > task-definition.json

      - name: Update Task Definition
        run: echo "`jq '.containerDefinitions[0].image="${{ steps.build-image.outputs.image }}"' task-definition.json`" > task-definition.json
         
        
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: ${{ env.AWS_ECS_SERVICE }}
          cluster: ${{ env.AWS_ECS_CLUSTER }}


      - name: Force new Deployment
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --region ${{ secrets.AWS_REGION }} --force-new-deployment